apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asdad
  description: asdasd
  annotations: 
    github.com/project-slug: hmcts-test/test-access7
    backstage.io/github-actions-id: hmcts-test/test-access7
spec:
  type: service
  lifecycle: experimental
  owner: guest
